version: '3.9'
services: 
  mongodb:
    image: mongo:4-bionic
    volumes:
      - ./auth/data:/data/db
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    depends_on: 
      - mongodb
    environment: 
      JWT_SECRET: secret
      NODE_ENV: development
      MONGODB_URL: mongodb://mongodb/prodev-composed-auth
    volumes:
      - ./auth/src:/usr/src/app/src
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/data:/usr/src/app/data
      - ./app/src:/usr/src/app/src
  ghi:
    build: ./ghi
    ports:
      - "8910:80"
    volumes:
      - ./ghi/static:/usr/share/nginx/html
    depends_on: 
      - app
      - auth